import { IEnvironment, versionTest } from './environment.interface';

export const environment: IEnvironment = {
  production: false,
  role: 'Claim_ec',
  OidcClientSettings: {
    authority: 'https://componenteseguridadtest.tecnoquimicas.com',
    client_id: 'fa7af7c2-a746-016e-3649-733a12848f2c',
    scope: 'openid profile fuerza_campo_ri eficienciacampo_ra',
    silentRenew: true,
    renewTimeBeforeTokenExpiresInSeconds: 300,
  },
  //apiGateway: 'https://localhost:44370',
  apiGateway: 'https://eficienciacampodesaback.azurewebsites.net',
  local: false,
  pwa: false,
  training: 'https://eficienciacampotest-api-entrenamiento.azurewebsites.net',
  version: versionTest,
  phoneNumber: '01800',
  idCampoNomClipadre: '32',
  sucClipadre: '33',
  idCupoClipadre: '8',
  idsEncuestas: '01,02,03,04',
  nuevasVisitasMaxPlaneacion: '5',
  nuevasVisitasMaxEjecucion: '4',
  terceronombre: '1',
  terceroid: '2',
  terceroclase: '3',
  terceroquintil_rs: '4',
  tercerodireccion: '5',
  tercerotelefono: '6',
  tercerofrecuencia_visita: '7',
  tercerocupo_disponible: '8',
  tercerofecha_ultima_visita: '9',
  tercerocompromiso: '10',
  tercerocliente: '11',
  tercerocodigo_compania: '12',
  tercerorazon_social: '13',
  tercerociudad: '14',
  tercerobarrio: '15',
  terceroemail: '16',
  terceronit: '17',
  terceroclipadre: '18',
  tercerocelular: '19',
  tercerointeres: '20',
  terceroplazo: '21',
  terceroplazo_interno_especial: '22',
  terceroflag_interes: '23',
  terceroestado: '24',
  terceroemail_fec: '25',
  tercerotitulo_info_cliente: '#{tercero.titulo_info_cliente}#',
  tercerotitulo_info_admin_cliente: '#{tercero.titulo_info_admin_cliente}#',
  tercerotitulo_info_admin_det_cliente: '#{tercero.titulo_info_admin_det_cliente}#',
  tercerotitulo_info_admin_basica: '#{tercero.titulo_info_admin_basica}#',
  tercerotitulo_info_admin_cartera: '#{tercero.titulo_info_admin_cartera}#',
  terceronom_clipadre: '31',
  tercerosuc_clipadre: '32',
  terceroduracion_visita: '33',
  tercerotipo_cli_facturacion: '34',
  tipo_Cubrimiento: '35', // '#{tercero.tipo_Cubrimiento}#',
  tipo_Colocacion: '36',
  totales_campo_tipo_cli_fact: 'TIPO_CLI_FACTURACION',
  totales_tipo_campo: '1',
  totales_valor_campo: '0',
  totales_plan_id: '116',
  powerBi: {
    workspaceId: 'f9e5cfd5-13ce-4a67-8d2c-5f646a5d90dc',
    reportId: '8229d8c1-e80e-41b9-84e8-3ef5392382eb'
  },
  baseUri: 'http://localhost:4200',
  postLogoutRedirectUri: 'http://localhost:4200/home/inicio',
  limiteHoraAccion: '9',
  idQuota: "Cuota"
};